# /* ---- 💫 https://github.com/oniichanx 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(141314)
$foreground = rgb(E4DCDC)
$color0 = rgb(3C3B3B)
$color1 = rgb(480C11)
$color2 = rgb(4B1317)
$color3 = rgb(802C2E)
$color4 = rgb(6B4649)
$color5 = rgb(867474)
$color6 = rgb(867474)
$color7 = rgb(D0C4C5)
$color8 = rgb(92898A)
$color9 = rgb(5F1016)
$color10 = rgb(65191F)
$color11 = rgb(AA3B3D)
$color12 = rgb(8E5E61)
$color13 = rgb(B39A9B)
$color14 = rgb(B39A9B)
$color15 = rgb(D0C4C5)
