$SCRIPT = ~/.config/hypr/scripts

bind = , xf86audioraisevolume, exec, $SCRIPT/Volume.sh --inc 
bind = , xf86audiolowervolume, exec, $SCRIPT/Volume.sh --dec 
bind = , xf86AudioMicMute, exec, $SCRIPT/Volume.sh --toggle-mic 
bind = , xf86audioMute, exec, $SCRIPT/Volume.sh --toggle 

bind = , xf86KbdBrightnessDown, exec, $SCRIPT/BrightnessKbd.sh --dec 
bind = , xf86KbdBrightnessUp, exec, $SCRIPT/BrightnessKbd.sh --inc 

bind = , xf86MonBrightnessDown, exec, $SCRIPT/Brightness.sh --dec 
bind = , xf86MonBrightnessUp, exec, $SCRIPT/Brightness.sh --inc 