#####################
### LOOK AND FEEL ###
#####################

# Refer to https://wiki.hyprland.org/Configuring/Variable for more

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    #col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.active_border=rgb(cdd6f4)
    col.inactive_border = rgba(595959aa)


    layout = dwindle

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = true
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/#decoration for more

    active_opacity = 1.0
    inactive_opacity = 0.9
    fullscreen_opacity = 1.0

    dim_inactive = true
    dim_strength = 0.1
    dim_special = 0.8

    rounding = 5
    
    blur {

        # old v1
        #enabled = true
        #size = 3
        #passes = 1
        #new_optimizations = true

        # new v2
        enabled = true
        size = 6
        passes = 2
        ignore_opacity = true
        new_optimizations = true
        special = true
        popups = true
        
    }

    #blurls = lockscreen

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

}
