# /* ---- 💫 https://github.com/oniichanx 💫 ---- */  #
# For 3 monitors left monitors is transform 90 (fix for vm passtho)

monitor=desc:AOP 24MV1Y P 110804FA63W01,1920x1080@164,1080x840,1,bitdepth,8
monitor=desc:Acer Technologies Acer K242HL T1MSS0044208,1920x1080@60,3000x840,1,bitdepth,10
monitor=desc:Acer Technologies Acer K242HL T1MSS0044200,1920x1080@60,0x0,1,bitdepth,10,transform,1

# workspaces - Monitor rules
workspace=1,monitor:desc:Acer Technologies Acer K242HL T1MSS0044208,default:true
workspace=2,monitor:desc:AOP 24MV1Y P 110804FA63W01,default:true
workspace=3,monitor:desc:Acer Technologies Acer K242HL T1MSS0044200,default:true